import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertTriangle,
  ArrowDown,
  ArrowDownUp,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpCircle,
  Bot,
  ChevronDown,
  Cloud,
  Expand,
  Eye,
  EyeOff,
  FlipHorizontal,
  FlipHorizontal2,
  Footprints,
  Hand,
  HandMetal,
  HeartPulse,
  HelpCircle,
  Maximize2,
  Medal,
  MoveHorizontal,
  Music2,
  PersonStanding,
  Pointer,
  RefreshCw,
  Rotate3d,
  RotateCw,
  ScanEye,
  Shield,
  Skull,
  Sparkles,
  Swords,
  ThumbsUp,
  Trophy,
  Vibrate,
  Waves,
  Wind,
  Zap,
  ZoomIn,
  ZoomOut,
} from "lucide-react";
import type { ProceduralAnimationId, ProceduralCategory } from "@/lib/procedural/defs";

const CATEGORY_ICONS: Record<ProceduralCategory, LucideIcon> = {
  locomotion: Footprints,
  gesture: Hand,
  transition: Sparkles,
  effect: Zap,
  action: Swords,
};

const ANIMATION_ICONS: Record<ProceduralAnimationId, LucideIcon> = {
  idle: PersonStanding,
  walk: Footprints,
  run: Zap,
  strafe: MoveHorizontal,
  sneak: EyeOff,
  tiptoe: ArrowUp,
  zombie: Skull,
  robot: Bot,
  wave: Hand,
  point: Pointer,
  salute: Medal,
  bow: ChevronDown,
  shrug: HelpCircle,
  clap: HandMetal,
  thumbsUp: ThumbsUp,
  stretch: Maximize2,
  lookAround: ScanEye,
  nod: ArrowDownUp,
  jump: ArrowUpCircle,
  spin: RotateCw,
  dance: Music2,
  celebrate: Trophy,
  stumble: AlertTriangle,
  punch: Swords,
  kick: Footprints,
  dodge: Shield,
  fadeIn: Eye,
  fadeOut: EyeOff,
  popIn: ZoomIn,
  popOut: ZoomOut,
  riseUp: ArrowUp,
  dropDown: ArrowDown,
  slideInLeft: ArrowLeft,
  slideInRight: ArrowRight,
  slideOutLeft: ArrowLeft,
  slideOutRight: ArrowRight,
  flipIn: FlipHorizontal,
  flipOut: FlipHorizontal2,
  bounce: ArrowUpCircle,
  shake: Vibrate,
  wiggle: Waves,
  pulse: HeartPulse,
  float: Cloud,
  hover: Wind,
  squashStretch: Expand,
  spinFast: RotateCw,
  tumble: Rotate3d,
  growShrink: Expand,
  sway: MoveHorizontal,
  breathe: Wind,
  twist: RefreshCw,
};

export function getAnimationIcon(id: ProceduralAnimationId, category: ProceduralCategory): LucideIcon {
  return ANIMATION_ICONS[id] ?? CATEGORY_ICONS[category] ?? Activity;
}

export function getCategoryIcon(category: ProceduralCategory): LucideIcon {
  return CATEGORY_ICONS[category];
}
